In [9]:
import pandas as pd
import numpy as np
from narwhals import DataFrame
from streamlit import columns

d=pd.DataFrame(data=np.arange(0,24).reshape(6,4),
             index=["name1","name2","name3","name4","name3","name4"],
             columns=["num1","num2","num3","num4"])  # dataframe is use for creating the systematic data structure in

In [10]:
print(d.head())  # The head() method is use for showing the uppermost 5 rows of data in the table.

       num1  num2  num3  num4
name1     0     1     2     3
name2     4     5     6     7
name3     8     9    10    11
name4    12    13    14    15
name3    16    17    18    19

In [11]:
print(d.tail())  # The tail() method is use for showing the lowermost 5 rows of data in the table.

       num1  num2  num3  num4
name2     4     5     6     7
name3     8     9    10    11
name4    12    13    14    15
name3    16    17    18    19
name4    20    21    22    23

In [12]:
print(d.head(2))

       num1  num2  num3  num4
name1     0     1     2     3
name2     4     5     6     7

In [13]:
print(d.tail(2)) # we can also adjust the number of rows in it

       num1  num2  num3  num4
name3    16    17    18    19
name4    20    21    22    23

In [14]:
d.info()  # info is shows the information in the table, and we can see the datatype of the every row.

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, name1 to name4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   num1    6 non-null      int64
 1   num2    6 non-null      int64
 2   num3    6 non-null      int64
 3   num4    6 non-null      int64
dtypes: int64(4)
memory usage: 240.0+ bytes

In [15]:
d.describe()

            num1       num2       num3       num4
count   6.000000   6.000000   6.000000   6.000000
mean   10.000000  11.000000  12.000000  13.000000
std     7.483315   7.483315   7.483315   7.483315
min     0.000000   1.000000   2.000000   3.000000
25%     5.000000   6.000000   7.000000   8.000000
50%    10.000000  11.000000  12.000000  13.000000
75%    15.000000  16.000000  17.000000  18.000000
max    20.000000  21.000000  22.000000  23.000000

In [16]:
# Indexing
# colmnname, rowindex[Loc], rowindex columnindex number[.iloc]
d.head()

       num1  num2  num3  num4
name1     0     1     2     3
name2     4     5     6     7
name3     8     9    10    11
name4    12    13    14    15
name3    16    17    18    19

In [17]:
d[['num1', 'num2', 'num3']]  # by using column name !

       num1  num2  num3
name1     0     1     2
name2     4     5     6
name3     8     9    10
name4    12    13    14
name3    16    17    18
name4    20    21    22

In [27]:
d[['num1']]

       num1
name1     0
name2     4
name3     8
name4    12
name3    16
name4    20

In [19]:
type(d[['num1', 'num2', 'num3']]) # dataframes -> use double braces [[]] and multiple data on it.

pandas.core.frame.DataFrame

In [25]:
type(d['num4']) # series -> if we are use [] single square braces then it will become series with single data.

pandas.core.series.Series

In [29]:
# Loc parameter :
d.loc[['name1','name2']] # using row index name
# helpful when you want to use name for indexing

       num1  num2  num3  num4
name1     0     1     2     3
name2     4     5     6     7

In [32]:
# .iloc parameter :
d.iloc[0:3,1:3]
# useful when we use number for indexing out the value.

       num2  num3
name1     1     2
name2     5     6
name3     9    10

In [33]:
d.iloc[2:, 1:]

       num2  num3  num4
name3     9    10    11
name4    13    14    15
name3    17    18    19
name4    21    22    23

In [39]:
d.iloc[:,0:3:2]

       num1  num3
name1     0     2
name2     4     6
name3     8    10
name4    12    14
name3    16    18
name4    20    22

In [44]:
d.iloc[:,1:]

       num2  num3  num4
name1     1     2     3
name2     5     6     7
name3     9    10    11
name4    13    14    15
name3    17    18    19
name4    21    22    23

In [45]:
# convert dataframe into arrays
d.iloc[:,1:].values  # convert into arrays by values keyword

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [48]:
# basics operations :
d.isnull() # for finding the NaN ( NUll ) value !

        num1   num2   num3   num4
name1  False  False  False  False
name2  False  False  False  False
name3  False  False  False  False
name4  False  False  False  False
name3  False  False  False  False
name4  False  False  False  False

In [50]:
d.isnull().sum() # using sum() method for give the numbers in count.

num1    0
num2    0
num3    0
num4    0
dtype: int64

In [56]:
df = pd.DataFrame(data=[[1,np.nan,2],[1,3,4]], index=['row1', 'row2'], columns=['column1', 'column2', 'column3'])

df

      column1  column2  column3
row1        1      NaN        2
row2        1      3.0        4

In [57]:
df.isnull().sum()

column1    0
column2    1
column3    0
dtype: int64

In [59]:
df.isnull()

      column1  column2  column3
row1    False     True    False
row2    False    False    False

In [62]:
df.isnull().sum()==0

column1     True
column2    False
column3     True
dtype: bool

In [64]:
df['column1'].value_counts() # for counting the values

column1
1    2
Name: count, dtype: int64

In [66]:
df['column2'].unique() # shows unique values in Dataframe

array([nan,  3.])

In [68]:
df[df['column2']>2] # conditional indexing

      column1  column2  column3
row2        1      3.0        4