<a href="https://colab.research.google.com/github/aayushmanz/Python-for-ML/blob/main/Pandas%20in%20Python/practice_1_youtube_channel_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Level 1: The X-Ray (Basic Inspection)**

1. Question: *How many total rows and columns are there in this dataset? Also, write the code to check if there are any missing (NaN) values in the Country or Description columns. (Hint: Use shape and isnull().sum())*

In [ ]:
import pandas as pd

data = pd.read_csv('/content/global_top2000.csv')

data.set_index('Global Rank')

,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description
Global Rank,,,,,,,
1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,116005659874,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...
2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,335650634349,25757,IN,"Music can change the world"". T-Series is India..."
3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,187185678767,168366,IN,Sony Entertainment Television is one of the le...
4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,120113700862,1005,US,“Vlad & Niki” is the global preschool phenomen...
5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,123546449303,1589,US,"Welcome to Diana and Roma world - where Diana,..."
...,...,...,...,...,...,...,...
1996,UCwc-g1X6NyyI6xXAQlDkJqg,Chill Maar Bros,337000,17191136,73,IN,🏵️ Welcome to our channel where mysterious adv...
1997,UCUyuyEwo-3hxUyisaMdMfOw,Tomaz ZabZa,337000,119955639,289,TH,ดีใจที่ได้เจอทุกคนนะครับ! นี่คือพื้นที่ปลอดภั...
1998,UCwDTw-2gflgA4q0lY2CZaBQ,แอ็ค สมชื่อ,337000,53712205,1183,TH,"Thx.💜🤟🏻 100 Sub (21/03/2564) 1,000 Sub (4/05/2..."
1999,UCE16nGY2jA7OuCY_bs8BAyA,Epha VLR,337000,125019658,1213,TR,"Merhaba ben Epha, bu kanalda sadece valorant i..."
2000,UCPgp28O8dzgTSCyctHQP7xw,Sultan Roblox,337000,129437740,201,SA,انا سلطان صانع محتوى بسيط احب اسوي فيديوهات لل...

In [ ]:
data['Country'].hasnans # isko use kar ke check kar raha tha ki Nan value toh nhi hai na mere data base mein.

False

In [ ]:
data['Description'].hasnans

True

In [ ]:
data['Description'].isnull().sum()

np.int64(92)

In [ ]:
data['Description'].fillna('Desc Not Written !', inplace=True) # desc mein mili thi bas count karna nhi aaya kitni hai isliye

data['Description'].hasnans

False

In [ ]:
data.shape # the total index and columns.

(2000, 8)

In [ ]:
data.value_counts().sum() # total number of data is 2000

np.int64(2000)

In [ ]:
data.count() # haatho se count kar li column toh haahhahhahah baki index toh 2000 hai

Global Rank     2000
Channel ID      2000
Channel Name    2000
Subscribers     2000
Total Views     2000
Total Videos    2000
Country         2000
Description     2000
dtype: int64

**Level 2: The Filter (Filtering Data)**

2. Question: *Filter the dataset to extract only the channels that are from India (IN). How many total Indian channels are there in this Top 2000 list?*

In [ ]:
data = pd.read_csv('/content/global_top2000.csv')
data.head()

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,116005659874,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,335650634349,25757,IN,"Music can change the world"". T-Series is India..."
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,187185678767,168366,IN,Sony Entertainment Television is one of the le...
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,120113700862,1005,US,“Vlad & Niki” is the global preschool phenomen...
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,123546449303,1589,US,"Welcome to Diana and Roma world - where Diana,..."

In [ ]:
indian_channel = data[data['Country']=='IN']
print('Total number of indian channels : ',indian_channel.shape[0])

Total number of indian channels :  168

**Level 3: The Sorter (Sorting Data)**

3. Question: *Sort the data based on the Total Videos column in descending order. Find the names of the Top 5 channels that have uploaded the highest number of videos to date.*

In [ ]:
data

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description
0,1,UCX6OQ3DkcsbYNE6H8uQQuVA,MrBeast,474000000,116005659874,956,US,SUBSCRIBE FOR A COOKIE! New MrBeast or MrBeast...
1,2,UCq-Fj5jknLsUf-MWSy4_brA,T-Series,311000000,335650634349,25757,IN,"Music can change the world"". T-Series is India..."
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,187185678767,168366,IN,Sony Entertainment Television is one of the le...
3,4,UCvlE5gTbOvjiolFlEm-c_Ow,Vlad and Niki,149000000,120113700862,1005,US,“Vlad & Niki” is the global preschool phenomen...
4,5,UCk8GzjMOrta8yxDcKfylJYw,✿ Kids Diana Show,138000000,123546449303,1589,US,"Welcome to Diana and Roma world - where Diana,..."
...,...,...,...,...,...,...,...,...
1995,1996,UCwc-g1X6NyyI6xXAQlDkJqg,Chill Maar Bros,337000,17191136,73,IN,🏵️ Welcome to our channel where mysterious adv...
1996,1997,UCUyuyEwo-3hxUyisaMdMfOw,Tomaz ZabZa,337000,119955639,289,TH,ดีใจที่ได้เจอทุกคนนะครับ! นี่คือพื้นที่ปลอดภั...
1997,1998,UCwDTw-2gflgA4q0lY2CZaBQ,แอ็ค สมชื่อ,337000,53712205,1183,TH,"Thx.💜🤟🏻 100 Sub (21/03/2564) 1,000 Sub (4/05/2..."
1998,1999,UCE16nGY2jA7OuCY_bs8BAyA,Epha VLR,337000,125019658,1213,TR,"Merhaba ben Epha, bu kanalda sadece valorant i..."
1999,2000,UCPgp28O8dzgTSCyctHQP7xw,Sultan Roblox,337000,129437740,201,SA,انا سلطان صانع محتوى بسيط احب اسوي فيديوهات لل...

In [ ]:
data['Total Videos'].sort_values(ascending=False).head()

184    387807
547    239779
177    231466
67     179232
2      168366
Name: Total Videos, dtype: int64

In [ ]:
data.sort_values(by='Total Videos', ascending=False).head()

,Global Rank,Channel ID,Channel Name,Subscribers,Total Views,Total Videos,Country,Description
184,185,UC6pGDc4bFGD1_36IKv3FnYg,Crunchyroll,8490000,10513564195,387807,US,"Crunchyroll brings you clips, anime openings, ..."
547,548,UCx-KWLTKlB83hDI6UKECtJQ,HBO Max,3000000,2138864875,239779,US,A new era of Hogwarts begins. linktr.ee/hbomax
177,178,UCajVjEHDoVn_AHsunUZz_EQ,Republic Bangla,8790000,8230108330,231466,IN,"Official page of Bangla News, Bengali News & B..."
67,68,UCKy1dAqELo0zrOtPkf0eTMw,IGN,19800000,21190494351,179232,US,IGN brings you daily videos about the latest g...
2,3,UCpEhnqL0y41EpW2TvWAHD7Q,SET India,188000000,187185678767,168366,IN,Sony Entertainment Television is one of the le...