In [2]:
import pandas as pd
import numpy as np

movies = pd.read_csv('/workspaces/Python-for-ML/Database from Kaggle/imdb-top-1000.csv')
genres = movies.groupby('Genre')

In [3]:
# agg method
# passing dict
genres.agg({
    'Runtime': 'mean',
    'IMDB_Rating': 'mean',
    'No_of_Votes': 'sum',
    'Gross': 'sum',
    'Metascore': 'min'
})

              Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419     72282412  3.263226e+10       33.0
Adventure  134.111111     7.937500     22576163  9.496922e+09       41.0
Animation   99.585366     7.930488     21978630  1.463147e+10       61.0
Biography  136.022727     7.938636     24006844  8.276358e+09       48.0
Comedy     112.129032     7.901290     27620327  1.566387e+10       45.0
Crime      126.392523     8.016822     33533615  8.452632e+09       47.0
Drama      124.737024     7.957439     61367304  3.540997e+10       28.0
Family     107.500000     7.800000       551221  4.391106e+08       67.0
Fantasy     85.000000     8.000000       146222  7.827267e+08        NaN
Film-Noir  104.000000     7.966667       367215  1.259105e+08       94.0
Horror     102.090909     7.909091      3742556  1.034649e+09       46.0
Mystery    119.083333     7.975000      4203004  1.256417e+09       52.0
Thriller   108.000000     7.800000        27733  1.755074e+07       81.0
Western    148.250000     8.350000      1289665  5.822151e+07       69.0

In [4]:
# adding both the syntax 
genres.agg({
    'Runtime': ['mean','min'],
    'IMDB_Rating': ['mean','max'],
    'No_of_Votes': ['sum', 'max'],
    'Gross': 'sum',
    'Metascore': 'min'
})

              Runtime      IMDB_Rating      No_of_Votes           \
                 mean  min        mean  max         sum      max
Genre
Action     129.046512   45    7.949419  9.0    72282412  2303232
Adventure  134.111111   88    7.937500  8.6    22576163  1512360
Animation   99.585366   71    7.930488  8.6    21978630   999790
Biography  136.022727   93    7.938636  8.9    24006844  1213505
Comedy     112.129032   68    7.901290  8.6    27620327   939631
Crime      126.392523   80    8.016822  9.2    33533615  1826188
Drama      124.737024   64    7.957439  9.3    61367304  2343110
Family     107.500000  100    7.800000  7.8      551221   372490
Fantasy     85.000000   76    8.000000  8.1      146222    88794
Film-Noir  104.000000  100    7.966667  8.1      367215   158731
Horror     102.090909   71    7.909091  8.5     3742556   787806
Mystery    119.083333   96    7.975000  8.4     4203004  1129894
Thriller   108.000000  108    7.800000  7.8       27733    27733
Western    148.250000  132    8.350000  8.8     1289665   688390

                  Gross Metascore
                    sum       min
Genre
Action     3.263226e+10      33.0
Adventure  9.496922e+09      41.0
Animation  1.463147e+10      61.0
Biography  8.276358e+09      48.0
Comedy     1.566387e+10      45.0
Crime      8.452632e+09      47.0
Drama      3.540997e+10      28.0
Family     4.391106e+08      67.0
Fantasy    7.827267e+08       NaN
Film-Noir  1.259105e+08      94.0
Horror     1.034649e+09      46.0
Mystery    1.256417e+09      52.0
Thriller   1.755074e+07      81.0
Western    5.822151e+07      69.0

In [5]:
# passing list
genres[['Runtime', 'IMDB_Rating', 'No_of_Votes', 'Gross', 'Metascore']].agg(['min', 'max', 'mean'])

          Runtime                  IMDB_Rating                No_of_Votes  \
              min  max        mean         min  max      mean         min
Genre
Action         45  321  129.046512         7.6  9.0  7.949419       25312
Adventure      88  228  134.111111         7.6  8.6  7.937500       29999
Animation      71  137   99.585366         7.6  8.6  7.930488       25229
Biography      93  209  136.022727         7.6  8.9  7.938636       27254
Comedy         68  188  112.129032         7.6  8.6  7.901290       26337
Crime          80  229  126.392523         7.6  9.2  8.016822       27712
Drama          64  242  124.737024         7.6  9.3  7.957439       25088
Family        100  115  107.500000         7.8  7.8  7.800000      178731
Fantasy        76   94   85.000000         7.9  8.1  8.000000       57428
Film-Noir     100  108  104.000000         7.8  8.1  7.966667       59556
Horror         71  122  102.090909         7.6  8.5  7.909091       27007
Mystery        96  138  119.083333         7.6  8.4  7.975000       33982
Thriller      108  108  108.000000         7.8  7.8  7.800000       27733
Western       132  165  148.250000         7.8  8.8  8.350000       65659

                                         Gross                             \
               max           mean          min          max          mean
Genre
Action     2303232  420246.581395       3296.0  936662225.0  1.897224e+08
Adventure  1512360  313557.819444      61001.0  874211619.0  1.319017e+08
Animation   999790  268032.073171     128985.0  873839108.0  1.784326e+08
Biography  1213505  272805.045455      21877.0  753585104.0  9.404952e+07
Comedy      939631  178195.658065       1305.0  886752933.0  1.010572e+08
Crime      1826188  313398.271028       6013.0  790482117.0  7.899656e+07
Drama      2343110  212343.612457       3600.0  924558264.0  1.225259e+08
Family      372490  275610.500000    4000000.0  435110554.0  2.195553e+08
Fantasy      88794   73111.000000  337574718.0  445151978.0  3.913633e+08
Film-Noir   158731  122405.000000     449191.0  123353292.0  4.197018e+07
Horror      787806  340232.363636      89029.0  298791505.0  9.405902e+07
Mystery    1129894  350250.333333    1035953.0  474203697.0  1.047014e+08
Thriller     27733   27733.000000   17550741.0   17550741.0  1.755074e+07
Western     688390  322416.250000    5321508.0   31800000.0  1.455538e+07

          Metascore
                min    max       mean
Genre
Action         33.0   98.0  73.419580
Adventure      41.0  100.0  78.437500
Animation      61.0   96.0  81.093333
Biography      48.0   97.0  76.240506
Comedy         45.0   99.0  78.720000
Crime          47.0  100.0  77.080460
Drama          28.0  100.0  79.701245
Family         67.0   91.0  79.000000
Fantasy         NaN    NaN        NaN
Film-Noir      94.0   97.0  95.666667
Horror         46.0   97.0  80.000000
Mystery        52.0  100.0  79.125000
Thriller       81.0   81.0  81.000000
Western        69.0   90.0  78.250000

In [6]:
# Looping on groups

for group,data in genres :
    print(type(group), type(data))

<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>
<class 'str'> <class 'pandas.DataFrame'>

In [20]:

df = pd.DataFrame(columns=movies.columns)
print(df)
for group, data in genres:
    top_rated = data[data['IMDB_Rating'] == data['IMDB_Rating'].max()]
    df = pd.concat([df, top_rated], ignore_index=True)

df

Empty DataFrame
Columns: [Series_Title, Released_Year, Runtime, Genre, IMDB_Rating, Director, Star1, No_of_Votes, Gross, Metascore]
Index: []

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
1,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
2,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
3,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
4,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
5,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
6,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
7,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
8,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
9,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
10,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
11,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
12,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
13,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
14,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
15,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
16,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [21]:
# split ( apply ) combine
# apply -> builtin function

genres.apply(min)

Genre
Action       Director
Adventure    Director
Animation    Director
Biography    Director
Comedy       Director
Crime        Director
Drama        Director
Family       Director
Fantasy      Director
Film-Noir    Director
Horror       Director
Mystery      Director
Thriller     Director
Western      Director
dtype: str

In [34]:
# find number of movies starting with A for each group

def ayush(group):
    return group['Series_Title'].str.startswith('A').sum()
genres.apply(ayush)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [35]:
# other method : 

genres.apply(lambda group: group['Series_Title'].str.startswith('A').sum())

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [38]:
# find ranking of each movie in the group according to IMDB score

def rank_movie(group):
    group['Genre_Rank'] = group['IMDB_Rating'].rank(ascending=False)
    return group


genres.apply(rank_movie)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  Genre_Rank
Genre
Action   2        2303232  534858444.0       84.0         1.0
         5        1642758  377845905.0       94.0         2.0
         8        2067042  292576195.0       74.0         3.5
         10       1661481  315544750.0       92.0         3.5
         13       1485555  342551365.0       87.0         6.0
...                   ...          ...        ...         ...
Thriller 700        27733   17550741.0       81.0         1.0
Western  12        688390    6100000.0       90.0         1.0
         48        302844    5321508.0       80.0         2.0
         115       232772   15000000.0       74.0         3.0
         691        65659   31800000.0       69.0         4.0

[1000 rows x 10 columns]

In [39]:
# Find Normalized IMDB rating group wise 

def normal(group):
    group['norm_rating'] = group['IMDB_Rating'] - group['IMDB_Rating'].min()/(group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
    return group



genres.apply(normal)

/tmp/ipykernel_2001/1046970806.py:4: RuntimeWarning: divide by zero encountered in scalar divide
  group['norm_rating'] = group['IMDB_Rating'] - group['IMDB_Rating'].min()/(group['IMDB_Rating'].max() - group['IMDB_Rating'].min())

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore   norm_rating
Genre
Action   2        2303232  534858444.0       84.0  3.571429e+00
         5        1642758  377845905.0       94.0  3.471429e+00
         8        2067042  292576195.0       74.0  3.371429e+00
         10       1661481  315544750.0       92.0  3.371429e+00
         13       1485555  342551365.0       87.0  3.271429e+00
...                   ...          ...        ...           ...
Thriller 700        27733   17550741.0       81.0          -inf
Western  12        688390    6100000.0       90.0  1.000000e+00
         48        302844    5321508.0       80.0  7.000000e-01
         115       232772   15000000.0       74.0  5.000000e-01
         691        65659   31800000.0       69.0  7.105427e-15

[1000 rows x 10 columns]

In [ ]:
# looping on groups

In [44]:
# groupby on mutilple cols
duo = movies.groupby(['Director', 'Star1'])
# size
duo.size()
# get_group 
duo.get_group(('Aamir Khan', 'Amole Gupte'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

In [46]:
# find the most earing actor -> dirctor combo
duo['Gross'].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [51]:
# find teh best ( in - term of metascore(avg)) actor -> genre combo
movies.groupby(['Star1', 'Genre'])['Metascore'].mean().reset_index().sort_values('Metascore', ascending=False).head(1)

             Star1      Genre  Metascore
606  Peter O'Toole  Adventure      100.0

In [54]:
# agg multple groupby

duo[['Runtime', 'IMDB_Rating', 'No_of_Votes', 'Gross', 'Metascore']].agg(['min', 'max', 'mean'])

                                   Runtime             IMDB_Rating            \
                                       min  max   mean         min  max mean
Director            Star1
Aamir Khan          Amole Gupte        165  165  165.0         8.4  8.4  8.4
Aaron Sorkin        Eddie Redmayne     129  129  129.0         7.8  7.8  7.8
Abdellatif Kechiche Léa Seydoux        180  180  180.0         7.7  7.7  7.7
Abhishek Chaubey    Shahid Kapoor      148  148  148.0         7.8  7.8  7.8
Abhishek Kapoor     Amit Sadh          130  130  130.0         7.7  7.7  7.7
...                                    ...  ...    ...         ...  ...  ...
Zaza Urushadze      Lembit Ulfsak       87   87   87.0         8.2  8.2  8.2
Zoya Akhtar         Hrithik Roshan     155  155  155.0         8.1  8.1  8.1
                    Vijay Varma        154  154  154.0         8.0  8.0  8.0
Çagan Irmak         Çetin Tekindor     112  112  112.0         8.3  8.3  8.3
Ömer Faruk Sorak    Cem Yilmaz         127  127  127.0         8.0  8.0  8.0

                                   No_of_Votes                          Gross  \
                                           min     max      mean          min
Director            Star1
Aamir Khan          Amole Gupte         168895  168895  168895.0    1223869.0
Aaron Sorkin        Eddie Redmayne       89896   89896   89896.0  853090410.0
Abdellatif Kechiche Léa Seydoux         138741  138741  138741.0    2199675.0
Abhishek Chaubey    Shahid Kapoor        27175   27175   27175.0  218428303.0
Abhishek Kapoor     Amit Sadh            32628   32628   32628.0    1122527.0
...                                        ...     ...       ...          ...
Zaza Urushadze      Lembit Ulfsak        40382   40382   40382.0     144501.0
Zoya Akhtar         Hrithik Roshan       67927   67927   67927.0    3108485.0
                    Vijay Varma          31886   31886   31886.0    5566534.0
Çagan Irmak         Çetin Tekindor       78925   78925   78925.0  461855363.0
Ömer Faruk Sorak    Cem Yilmaz           56960   56960   56960.0  196206077.0

                                                             Metascore        \
                                            max         mean       min   max
Director            Star1
Aamir Khan          Amole Gupte       1223869.0    1223869.0       NaN   NaN
Aaron Sorkin        Eddie Redmayne  853090410.0  853090410.0      77.0  77.0
Abdellatif Kechiche Léa Seydoux       2199675.0    2199675.0      89.0  89.0
Abhishek Chaubey    Shahid Kapoor   218428303.0  218428303.0       NaN   NaN
Abhishek Kapoor     Amit Sadh         1122527.0    1122527.0      40.0  40.0
...                                         ...          ...       ...   ...
Zaza Urushadze      Lembit Ulfsak      144501.0     144501.0      73.0  73.0
Zoya Akhtar         Hrithik Roshan    3108485.0    3108485.0       NaN   NaN
                    Vijay Varma       5566534.0    5566534.0      65.0  65.0
Çagan Irmak         Çetin Tekindor  461855363.0  461855363.0       NaN   NaN
Ömer Faruk Sorak    Cem Yilmaz      196206077.0  196206077.0       NaN   NaN


                                    mean
Director            Star1
Aamir Khan          Amole Gupte      NaN
Aaron Sorkin        Eddie Redmayne  77.0
Abdellatif Kechiche Léa Seydoux     89.0
Abhishek Chaubey    Shahid Kapoor    NaN
Abhishek Kapoor     Amit Sadh       40.0
...                                  ...
Zaza Urushadze      Lembit Ulfsak   73.0
Zoya Akhtar         Hrithik Roshan   NaN
                    Vijay Varma     65.0
Çagan Irmak         Çetin Tekindor   NaN
Ömer Faruk Sorak    Cem Yilmaz       NaN

[898 rows x 15 columns]