<a href="https://colab.research.google.com/github/aayushmanz/Python-for-ML/blob/main/Pandas%20in%20Python/Maths%20Methods%20and%20Select%20(cols%2C%20rows%2C%20both)%20in%20DataFrames.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Math Methods**

In [1]:
# Sum -> axis arguements

import pandas as pd
import numpy as np

student_dict = {
    'iq' : [80,70,120,80,0,0],
    'marks' : [100,70,100,50,0,0],
    'package' : [10,7,14,2,0,0]
}
std_dict = pd.DataFrame(student_dict)
std_dict.sum()

iq         350
marks      320
package     33
dtype: int64

In [2]:
# Sum :
std_dict.sum(axis=1)

0    190
1    147
2    234
3    132
4      0
5      0
dtype: int64

In [3]:
# mean, median, mode
std_dict.mean(axis=1)

0    63.333333
1    49.000000
2    78.000000
3    44.000000
4     0.000000
5     0.000000
dtype: float64

In [4]:
std_dict.mode(axis=1)

      0      1      2
0  10.0   80.0  100.0
1  70.0    NaN    NaN
2  14.0  100.0  120.0
3   2.0   50.0   80.0
4   0.0    NaN    NaN
5   0.0    NaN    NaN

In [5]:
std_dict.median(axis=1)

0     80.0
1     70.0
2    100.0
3     50.0
4      0.0
5      0.0
dtype: float64

In [6]:
# var
std_dict.var(axis=True)

0    2233.333333
1    1323.000000
2    3172.000000
3    1548.000000
4       0.000000
5       0.000000
dtype: float64

**2. Selecting cols in a dataframes :**

In [7]:
movies = pd.read_csv('/content/movies.csv')
movies.head(1)

FileNotFoundError: [Errno 2] No such file or directory: '/content/movies.csv'

In [ ]:
# single cols :
movies['story'] # single column is series

0       Divided over five chapters  the film chronicle...
1       The story revolves around a cricket match betw...
2       Based on the memoir by Indian policy analyst S...
3       The movie focuses on existing malpractices in ...
4       While gay rights and marriage equality has bee...
                              ...
1624    Raj Dixit lives with his younger brother  Rahu...
1625    Hindi pop-star  Sarina Devan  lives a wealthy ...
1626    Village born Lalloo re-locates to Bombay  and ...
1627    Shinda tries robbing a bank so he can be wealt...
1628    Sara and Ashar are childhood friends who share...
Name: story, Length: 1629, dtype: object

In [ ]:
# multiple cols :

movies[['title_x','genres','actors']] # multiple columns is DataFrames

,title_x,genres,actors
0,Uri: The Surgical Strike,Action|Drama|War,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
1,Battalion 609,War,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...
2,The Accidental Prime Minister (film),Biography|Drama,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...
3,Why Cheat India,Crime|Drama,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...
4,Evening Shadows,Drama,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...
...,...,...,...
1624,Tera Mera Saath Rahen,Drama,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...
1625,Yeh Zindagi Ka Safar,Drama,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...
1626,Sabse Bada Sukh,Comedy|Drama,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...
1627,Daaka,Action,Gippy Grewal|Zareen Khan|
1628,Humsafar,Drama|Romance,Fawad Khan|

In [17]:
import pandas as pd

student_dict = {
    'name' : ['ayush','raju','sumit','arti','prachi','riddhi'],
    'iq' : [80,70,120,80,0,0],
    'marks' : [100,70,100,50,0,0],
    'package' : [10,7,14,2,0,0]
}
std_dict = pd.DataFrame(student_dict)
std_dict.set_index('name', inplace=True) # becz of this i can make my column as a index.

**3. Selecting rows in a dataframes :**


*   iloc -> searches using index positions
*   loc -> searches using index labels

1. iloc()

In [3]:
# single row :
movies =  pd.read_csv('/workspaces/Python-for-ML/Database from Kaggle/movies.csv')
movies.iloc[0]  # iloc use numbers for getting the data from the data base.
# i use the 0 as a index positon for getting the first data

title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: 0, dtype: object

In [4]:
# multiple row :
movies.iloc[0:5] # now i get 0 to 5 movies on index

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [5]:
movies.iloc[5:16:2]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)
7,Bombairiya,tt4971258,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Bombairiya,Bombairiya,Bombairiya,0,2019,104,Comedy|Crime|Drama,4.3,295,It follows the story of Meghna who gets embro...,It follows the story of Meghna who gets embro...,They didn't mean to change the world.,Radhika Apte|Akshay Oberoi|Siddhanth Kapoor|Ra...,NaN,18 January 2019 (India)
9,Thackeray (film),tt7777196,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Thackeray_(film),Thackeray,Thackeray,0,2019,120,Biography|Drama,5.1,2301,Balasaheb Thackrey works as a cartoonist for a...,Biographical account of Shiv Sena Supremo Bal...,NaN,Nawazuddin Siddiqui|Amrita Rao|Abdul Quadir Am...,NaN,25 January 2019 (India)
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA)
13,Total Dhamaal,tt7639372,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Total_Dhamaal,Total Dhamaal,Total Dhamaal,0,2019,130,Action|Adventure|Comedy,4.3,4817,Total Dhamaal is the third instalment in the D...,A group of people learn about a hidden treasur...,The Wildest Adventure Ever,Ajay Devgn|Madhuri Dixit|Anil Kapoor|Riteish D...,NaN,22 February 2019 (India)
15,Badla (2019 film),tt8130968,https://upload.wikimedia.org/wikipedia/en/0/0c...,https://en.wikipedia.org/wiki/Badla_(2019_film),Badla,Badla,0,2019,118,Crime|Drama|Mystery,7.9,15499,Naina Sethi a successful entrepreneur finds he...,A dynamic young entrepreneur finds herself loc...,NaN,Amitabh Bachchan|Taapsee Pannu|Amrita Singh|An...,1 win,8 March 2019 (India)

In [23]:
movies.iloc[0:3,0:3]

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In [6]:
# fancy index :

movies.iloc[[0,4,5]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)

2. loc():

In [18]:
# loc :

std_dict

         iq  marks  package
name
ayush    80    100       10
raju     70     70        7
sumit   120    100       14
arti     80     50        2
prachi    0      0        0
riddhi    0      0        0

In [19]:
std_dict.loc['ayush']

iq          80
marks      100
package     10
Name: ayush, dtype: int64

In [21]:
std_dict.loc['ayush':'arti']

        iq  marks  package
name
ayush   80    100       10
raju    70     70        7
sumit  120    100       14
arti    80     50        2

In [26]:
movies.loc[0:3,'title_x':'poster_path']

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...